services:
  - type: web
    name: mhdv-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_PASSWORD
        value: mhdvmim
      - key: DB_PATH
        value: mhdv_bot.db
